site_name: OpenRoadSim Documentation
repo_url: https://github.com/karthagokul/openroadsim
theme:
  name: material
  language: en

plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - API Reference:
      - Core Modules: core.md
      - Utility Modules: utils.md
      - Plugins: plugins.md
