site_name: OpenRoadSim
site_url: https://karthagokul.github.io/openroadsim/ # IMPORTANT: Set this to your actual deployed URL
repo_url: https://github.com/karthagokul/openroadsim
repo_name: karthagokul/openroadsim # Optional, but good for display
edit_uri: blob/main/docs/ # Allows "Edit this page" link to point to the source file

# Copyright information, typically in the footer
copyright: Copyright &copy; 2025 Gokul Kartha and OpenRoadSim Contributors

theme:
  name: material
  language: en


plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - API Reference:
      - Core Modules: core.md
      - Utility Modules: utils.md
  - Plugins:
      - Overview: plugins/index.md
      - CAN Plugin: plugins/can.md
      - Echo Plugin: plugins/echo.md
      - GPS Plugin: plugins/gps.md
      - Media Plugin: plugins/media.md
      - Replay GPS Plugin: plugins/replay_gps.md
